from django.urls import path

from . import views

urlpatterns = [
    path("companies/", views.CompanyListView.as_view(), name="company-list"),
    path("companies/new/", views.CompanyCreateView.as_view(), name="company-create"),
    path(
        "companies/<int:pk>/",
        views.CompanyDetailView.as_view(),
        name="company-detail",
    ),
    path(
        "companies/<int:pk>/edit/",
        views.CompanyUpdateView.as_view(),
        name="company-edit",
    ),
    path(
        "companies/<int:pk>/delete/",
        views.CompanyDeleteView.as_view(),
        name="company-delete",
    ),
    path(
        "companies/<int:company_pk>/log-contact/",
        views.LogContactView.as_view(),
        name="company-log-contact",
    ),
    path(
        "companies/<int:company_pk>/contacts/new/",
        views.ContactCreateView.as_view(),
        name="contact-create",
    ),
    path(
        "contacts/<int:pk>/edit/",
        views.ContactUpdateView.as_view(),
        name="contact-edit",
    ),
    path(
        "contacts/<int:pk>/delete/",
        views.ContactDeleteView.as_view(),
        name="contact-delete",
    ),
    path(
        "companies/<int:company_pk>/comments/new/",
        views.CompanyCommentCreateView.as_view(),
        name="company-comment-create",
    ),
    path(
        "company-comments/<int:pk>/edit/",
        views.CompanyCommentUpdateView.as_view(),
        name="company-comment-edit",
    ),
    path(
        "company-comments/<int:pk>/delete/",
        views.CompanyCommentDeleteView.as_view(),
        name="company-comment-delete",
    ),
    path("candidates/", views.CandidateListView.as_view(), name="candidate-list"),
    path(
        "candidates/new/",
        views.CandidateCreateView.as_view(),
        name="candidate-create",
    ),
    path(
        "candidates/<int:pk>/",
        views.CandidateDetailView.as_view(),
        name="candidate-detail",
    ),
    path(
        "candidates/<int:pk>/edit/",
        views.CandidateUpdateView.as_view(),
        name="candidate-edit",
    ),
    path(
        "candidates/<int:pk>/delete/",
        views.CandidateDeleteView.as_view(),
        name="candidate-delete",
    ),
    path(
        "candidates/<int:pk>/flag/",
        views.CandidateFlagView.as_view(),
        name="candidate-flag",
    ),
    path(
        "candidates/<int:pk>/unflag/",
        views.CandidateUnflagView.as_view(),
        name="candidate-unflag",
    ),
    path(
        "candidates/<int:candidate_pk>/comments/new/",
        views.CandidateCommentCreateView.as_view(),
        name="candidate-comment-create",
    ),
    path(
        "candidate-comments/<int:pk>/edit/",
        views.CandidateCommentUpdateView.as_view(),
        name="candidate-comment-edit",
    ),
    path(
        "candidate-comments/<int:pk>/delete/",
        views.CandidateCommentDeleteView.as_view(),
        name="candidate-comment-delete",
    ),
    path("pipeline/", views.PipelineView.as_view(), name="pipeline"),
]
