# Generated by Django 5.2.15 on 2026-07-06 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_candidate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='name',
            field=models.CharField(db_collation='sv-SE-x-icu', max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(db_collation='sv-SE-x-icu', max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_collation='sv-SE-x-icu', max_length=255),
        ),
    ]
