# Generated by Django 5.2.15 on 2026-07-06 05:30

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_alter_candidate_name_alter_company_name_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='candidate',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', 'location', 'skills', config='simple'), name='candidate_search_idx'),
        ),
    ]
