# Generated by Django 5.2.15 on 2026-07-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0006_candidate_candidate_search_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='company',
            name='location',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
    ]
