# Generated by Django 5.2.15 on 2026-07-10 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
