# Generated by Django 5.2.15 on 2026-08-06 09:52

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_tag_company_tags'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidate',
            name='candidate_search_idx',
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.search.SearchVector('name', 'skills', config='simple'), name='candidate_search_idx'),
        ),
    ]
